### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Aloso** [Whiley/STD.wy#24]
The standard library doesn't include a FOSS license, and the source files state that `David J. Pearce` is the sole copyright owner, "all rights reserved". As a contributor, I would be hesitant to contribute to non-free software. Consider adding a FOSS license to the standard library and removing the copyright notices in the source files.

**Comment by DavePearce** [comment]
Well, the files are listed as BSD-3 clause --- that is an FOSS license, right?  To be fair its not something I've given a lot of thought to at this stage.

However, the rest of the Whiley compiler is Apache 2.0, so I could just move to that.

**Comment by DavePearce** [comment]
Done!
