### ISSUE TITLE
Property "is_start_four" actually tests for start of a three-byte code

### ISSUE THREAD

**Issue by ngoriyasjil** [Whiley/STD.wy#25]
https://github.com/Whiley/STD.wy/blob/3b6ce291553f2d85647e610a35233ff0546c7821/src/whiley/std/utf8.whiley#L44&L45

**Comment by DavePearce** [comment]
Yeah, that doesn't look right!  To be fair, I haven't really tested the utf8 support at all.  Its more of a place holder to give me a feel for how it would look :|
