### ISSUE TITLE
Invalid postcondition for ascii append()

### ISSUE THREAD

**Issue by JC626** [Whiley/STD.wy#4]
The postcondition append() function looks incorrect

Specifically the postcondition for `ensures all { k in 0..|s2| | r[k+|s1|] == s1[k] }`

Instead, I think this should be **s2[k]** i.e.

`ensures all { k in 0..|s2| | r[k+|s1|] == s2[k] }`

**Comment by DavePearce** [comment]
Where's my counterexample? :)

**Comment by DavePearce** [comment]
I think you are correct, but that this was already corrected.  The post condition currently reads:

```
ensures all { k in 0..|rhs| | r[k+|lhs|] == rhs[k] }
```

Is this because you used the download version, rather than cloning the repo?  Otherwise, I'm not sure how this happened.

**Comment by DavePearce** [comment]
No, wait, I see!!  It's `ascii::append`, not `array::append`.  Looks like I corrected array one but not the string one.

**Comment by DavePearce** [comment]
Fixed now!
